const TIME_ZONE = "Asia/Manila";
const LOGIN_LOCKOUT_MAX_ATTEMPTS = 5;
const LOGIN_LOCKOUT_DURATION_MS = 15 * 60 * 1000;
const GUEST_EMAIL_DOMAIN = "guest.internal";
const GUEST_RECOVERY_WINDOW_DAYS = 60;
const GUEST_RECOVERY_CREDENTIAL_TTL_MS = 24 * 60 * 60 * 1000;
const GUEST_CREATION_LIMIT_WINDOW_MS = 60 * 60 * 1000;
const GUEST_CREATION_LIMIT_MAX = 10;

module.exports = {
  TIME_ZONE,
  LOGIN_LOCKOUT_MAX_ATTEMPTS,
  LOGIN_LOCKOUT_DURATION_MS,
  GUEST_EMAIL_DOMAIN,
  GUEST_RECOVERY_WINDOW_DAYS,
  GUEST_RECOVERY_CREDENTIAL_TTL_MS,
  GUEST_CREATION_LIMIT_WINDOW_MS,
  GUEST_CREATION_LIMIT_MAX,
};